language: csharp
mono: latest
dotnet: 3.1
jobs:
  include:
    - stage: "Build"
      if: branch != docs
      install: dotnet restore
      script: dotnet build
    - stage: "Generate Documentation"
      if: branch = master OR branch = docs
      install:
        - dotnet restore
        - nuget install docfx.console -Version $DOCFX_VERSION
      script:
        - mono ./docfx.console.$DOCFX_VERSION/tools/docfx.exe metadata docfx_project/docfx.json
        - mono ./docfx.console.$DOCFX_VERSION/tools/docfx.exe build docfx_project/docfx.json
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: docfx_project/_site
        fqdn: tenor-client.halomademeapc.com
        on:
          branch: 
          - master
    - stage: "Run Tests"
      if: branch != master AND branch != docs
      install: dotnet restore
      script: dotnet test tests/Tenor.Tests/Tenor.Tests.csproj --verbosity detailed
    - stage: "Publish to NuGet"
      if: branch = master
      install: dotnet restore
      script: 
        - dotnet build
        - dotnet publish -c release
        - dotnet pack -c release --include-symbols -o publish
        - dotnet nuget push publish/*.nupkg --skip-duplicate -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json